# This is a basic workflow to help you get started with Actions

name: Push to Public

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout private repo
        uses: actions/checkout@v2
        with:
          repository: du-cloud-soc/cloud-workshops-private
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main

      - name: Generate App Token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      # - name: Configure Git
      #   run: |
      #     git config --global user.name "DU Cloud Society App"
      #     git config --global user.email "du-cloud-soc+github-actions[bot]@users.noreply.github.com"
  
      - name: Push to public repo
        env:
          PUBLIC_REPO_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          git remote add public-repo https://$PUBLIC_REPO_TOKEN@github.com/du-cloud-soc/cloud-workshops.git
          git push public-repo main --force

